### PR TITLE
Add book validation

### PR DESCRIPTION
**Pull request by godiard**

### CODE REVIEW

**Comment by godiard** [comment]
This address https://github.com/PathagarBooks/pathagar/issues/56

**Comment by sethwoodworth** [comment]
Whoops. I merged these out of order and now they wont merge cleanly.  Would you mind resubmitting?  Otherwise I can rebase this PR for you.

**Comment by godiard** [comment]
No problem, I will rebase and send another pr

**Comment by godiard** [comment]
New pr replacing this is https://github.com/PathagarBooks/pathagar/pull/62

**Pull request closed without merging**
